# henhouse.toml: config file for henhouse cli.
# Please check all values before running henhouse.

[Database]
connection = "user=postgres dbname=henhouse sslmode=disable"
max_connections = 90 # should be less than same value in postgresql.conf
