# henhouse.toml: config file for henhouse
# Please check all values before running henhouse.

log_file = "/tmp/henhouse.log"

# Path to directory contains task xml files
task_dir = "/home/mikhail/dev/go/src/github.com/jollheef/henhouse/config/tasks/"

[Database]
connection = "user=postgres dbname=henhouse sslmode=disable"
max_connections = 90 # should be less than same value in postgresql.conf
safe_reinit = false # disallow reinit after game start

[Scoreboard]
www_path = "/home/mikhail/dev/go/src/github.com/jollheef/henhouse/scoreboard/www"
addr = ":8000"

[WebsocketTimeout]
info = "1s"
scoreboard = "10s"
tasks = "10s"

[TaskPrice]
# for correct work with small amount of teams
use_teams_base = true
teams_base = 20
# 500 if percent of solve less than value
p500 = 10
p400 = 15
p300 = 30
# 200 if percent of solve less than value
p200 = 50
# other 100

[Game]
start = "Nov 17 10:00 2015"
end = "Dec 31 23:59 2015"

[Flag]
# timeout between send flags
send_timeout = "1s"

[Task]
# timeout after send correct flag before open next task
open_timeout = "1m"
# auto open task after previous solved
auto_open = true
auto_open_timeout = "6h"

[[Teams]]
name = "FooTeam"
description = "Foo test team"
token = "33"

[[Teams]]
name = "BarTeam"
description = "Bar test team"
token = "22"

[[Teams]]
name = "Admin"
test = true
token = "11"
